"""Static seed datasets: NIST controls, assets, findings, risks."""
from __future__ import annotations

from app.models.enums import (
    AssetStatus,
    AssetType,
    ControlImplementationStatus,
    Criticality,
    Environment,
    FindingStatus,
    RemediationStatus,
    Severity,
)

FAMILY_NAMES = {
    "AC": "Access Control",
    "IA": "Identification and Authentication",
    "AU": "Audit and Accountability",
    "SC": "System and Communications Protection",
    "SI": "System and Information Integrity",
}

# Example NIST 800-53 controls
CONTROLS: list[dict] = [
    {
        "control_id": "AC-2",
        "family": "AC",
        "title": "Account Management",
        "description": "Manage information system accounts, including establishing, activating, modifying, reviewing, disabling, and removing accounts.",
        "implementation_status": ControlImplementationStatus.PARTIALLY_IMPLEMENTED,
    },
    {
        "control_id": "AC-3",
        "family": "AC",
        "title": "Access Enforcement",
        "description": "Enforce approved authorizations for logical access to information and system resources in accordance with applicable access control policies.",
        "implementation_status": ControlImplementationStatus.IMPLEMENTED,
    },
    {
        "control_id": "AC-6",
        "family": "AC",
        "title": "Least Privilege",
        "description": "Employ the principle of least privilege, allowing only authorized accesses for users which are necessary to accomplish assigned organizational tasks.",
        "implementation_status": ControlImplementationStatus.NOT_IMPLEMENTED,
    },
    {
        "control_id": "IA-2",
        "family": "IA",
        "title": "Identification and Authentication (Organizational Users)",
        "description": "Uniquely identify and authenticate organizational users and associate that unique identification with processes acting on behalf of those users.",
        "implementation_status": ControlImplementationStatus.PARTIALLY_IMPLEMENTED,
    },
    {
        "control_id": "IA-5",
        "family": "IA",
        "title": "Authenticator Management",
        "description": "Manage information system authenticators including verifying identity, establishing content, and enforcing minimum and maximum lifetime restrictions.",
        "implementation_status": ControlImplementationStatus.NOT_IMPLEMENTED,
    },
    {
        "control_id": "AU-2",
        "family": "AU",
        "title": "Event Logging",
        "description": "Identify the types of events that the system is capable of logging in support of the audit function.",
        "implementation_status": ControlImplementationStatus.IMPLEMENTED,
    },
    {
        "control_id": "AU-6",
        "family": "AU",
        "title": "Audit Record Review, Analysis, and Reporting",
        "description": "Review and analyze system audit records for indications of inappropriate or unusual activity and report findings.",
        "implementation_status": ControlImplementationStatus.NOT_IMPLEMENTED,
    },
    {
        "control_id": "SC-7",
        "family": "SC",
        "title": "Boundary Protection",
        "description": "Monitor and control communications at the external managed interfaces to the system and at key internal managed interfaces within the system.",
        "implementation_status": ControlImplementationStatus.PARTIALLY_IMPLEMENTED,
    },
    {
        "control_id": "SI-4",
        "family": "SI",
        "title": "System Monitoring",
        "description": "Monitor the system to detect attacks, indicators of potential attacks, and unauthorized local, network, and remote connections.",
        "implementation_status": ControlImplementationStatus.PARTIALLY_IMPLEMENTED,
    },
]

ASSETS: list[dict] = [
    {
        "name": "prod-web-01",
        "owner": "Jane Smith",
        "business_unit": "Engineering",
        "asset_type": AssetType.SERVER,
        "criticality": Criticality.CRITICAL,
        "operating_system": "Ubuntu 22.04 LTS",
        "ip_address": "10.0.1.10",
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "prod-db-01",
        "owner": "Carlos Diaz",
        "business_unit": "Data Platform",
        "asset_type": AssetType.SERVER,
        "criticality": Criticality.CRITICAL,
        "operating_system": "Amazon Linux 2",
        "ip_address": "10.0.1.20",
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "corp-fw-01",
        "owner": "Network Team",
        "business_unit": "IT Operations",
        "asset_type": AssetType.NETWORK_DEVICE,
        "criticality": Criticality.HIGH,
        "operating_system": "PAN-OS 11",
        "ip_address": "10.0.0.1",
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "finance-workstation-12",
        "owner": "Maria Lopez",
        "business_unit": "Finance",
        "asset_type": AssetType.WORKSTATION,
        "criticality": Criticality.MEDIUM,
        "operating_system": "Windows 11 Pro",
        "ip_address": "10.0.5.42",
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "s3-customer-data",
        "owner": "Platform Team",
        "business_unit": "Data Platform",
        "asset_type": AssetType.CLOUD_RESOURCE,
        "criticality": Criticality.CRITICAL,
        "operating_system": "AWS S3",
        "ip_address": None,
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "billing-app",
        "owner": "Product Team",
        "business_unit": "Engineering",
        "asset_type": AssetType.APPLICATION,
        "criticality": Criticality.HIGH,
        "operating_system": "N/A",
        "ip_address": None,
        "environment": Environment.PRODUCTION,
        "status": AssetStatus.ACTIVE,
    },
    {
        "name": "staging-web-01",
        "owner": "Jane Smith",
        "business_unit": "Engineering",
        "asset_type": AssetType.SERVER,
        "criticality": Criticality.LOW,
        "operating_system": "Ubuntu 22.04 LTS",
        "ip_address": "10.1.1.10",
        "environment": Environment.STAGING,
        "status": AssetStatus.ACTIVE,
    },
]

# Findings reference assets by name; the seeder resolves the FK.
FINDINGS: list[dict] = [
    {
        "title": "Firewall Disabled",
        "description": "The host-based firewall service is disabled on the perimeter device, leaving inbound ports exposed.",
        "severity": Severity.CRITICAL,
        "status": FindingStatus.OPEN,
        "source": "Nessus",
        "cve": None,
        "evidence": "systemctl status firewalld -> inactive (dead)",
        "asset": "corp-fw-01",
        "detection_offset_days": 4,
    },
    {
        "title": "Weak Password Policy",
        "description": "Domain password policy allows 6-character passwords with no complexity or rotation requirements.",
        "severity": Severity.HIGH,
        "status": FindingStatus.OPEN,
        "source": "Manual Review",
        "cve": None,
        "evidence": "GPO: minimum length 6, complexity disabled.",
        "asset": "finance-workstation-12",
        "detection_offset_days": 9,
    },
    {
        "title": "Excessive Administrator Privileges",
        "description": "Twelve standard users hold local administrator rights beyond business need, violating least privilege.",
        "severity": Severity.HIGH,
        "status": FindingStatus.IN_PROGRESS,
        "source": "CIS-CAT",
        "cve": None,
        "evidence": "net localgroup administrators",
        "asset": "prod-web-01",
        "detection_offset_days": 15,
    },
    {
        "title": "Missing Security Logging",
        "description": "Security event logging and centralized log review are not configured on the database server.",
        "severity": Severity.MEDIUM,
        "status": FindingStatus.OPEN,
        "source": "Manual Review",
        "cve": None,
        "evidence": "No auditd rules; no SIEM forwarding.",
        "asset": "prod-db-01",
        "detection_offset_days": 22,
    },
    {
        "title": "MFA Not Enforced for Admin Console",
        "description": "Cloud administrator accounts can authenticate with a single factor; MFA is not enforced.",
        "severity": Severity.CRITICAL,
        "status": FindingStatus.OPEN,
        "source": "Cloud Posture Scan",
        "cve": None,
        "evidence": "IAM policy lacks aws:MultiFactorAuthPresent condition.",
        "asset": "s3-customer-data",
        "detection_offset_days": 30,
    },
    {
        "title": "Outdated OpenSSL (CVE-2023-0286)",
        "description": "Server runs an OpenSSL version vulnerable to a type confusion flaw enabling potential DoS.",
        "severity": Severity.HIGH,
        "status": FindingStatus.IN_PROGRESS,
        "source": "OpenVAS",
        "cve": "CVE-2023-0286",
        "evidence": "openssl version -> 1.1.1f",
        "asset": "staging-web-01",
        "detection_offset_days": 45,
    },
    {
        "title": "Stale User Accounts",
        "description": "Multiple user accounts have not logged in for over 180 days and remain enabled.",
        "severity": Severity.MEDIUM,
        "status": FindingStatus.OPEN,
        "source": "Manual Review",
        "cve": None,
        "evidence": "Last logon timestamps exceed 180 days for 8 accounts.",
        "asset": "billing-app",
        "detection_offset_days": 60,
    },
    {
        "title": "Unauthorized Access Attempt Detected",
        "description": "Endpoint monitoring detected repeated failed access attempts without alerting due to missing detection rules.",
        "severity": Severity.LOW,
        "status": FindingStatus.RESOLVED,
        "source": "EDR",
        "cve": None,
        "evidence": "5 failed RDP attempts from external IP.",
        "asset": "finance-workstation-12",
        "detection_offset_days": 80,
    },
]

REMEDIATIONS: list[dict] = [
    {
        "task": "Re-enable and harden host firewall",
        "description": "Enable firewalld, define ingress rules, and validate boundary protection.",
        "owner": "Network Team",
        "status": RemediationStatus.IN_PROGRESS,
        "priority": Severity.CRITICAL,
        "due_offset_days": 7,
        "finding_title": "Firewall Disabled",
    },
    {
        "task": "Update domain password policy",
        "description": "Enforce 14-char minimum, complexity, and 90-day rotation.",
        "owner": "IT Operations",
        "status": RemediationStatus.NOT_STARTED,
        "priority": Severity.HIGH,
        "due_offset_days": 14,
        "finding_title": "Weak Password Policy",
    },
    {
        "task": "Remove excessive admin rights",
        "description": "Revoke local admin from non-privileged users; implement JIT access.",
        "owner": "Security Analyst",
        "status": RemediationStatus.IN_PROGRESS,
        "priority": Severity.HIGH,
        "due_offset_days": 10,
        "finding_title": "Excessive Administrator Privileges",
    },
    {
        "task": "Enforce MFA on cloud admin accounts",
        "description": "Apply IAM policy requiring MFA for all administrative actions.",
        "owner": "Platform Team",
        "status": RemediationStatus.BLOCKED,
        "priority": Severity.CRITICAL,
        "due_offset_days": 5,
        "finding_title": "MFA Not Enforced for Admin Console",
    },
    {
        "task": "Patch OpenSSL to latest version",
        "description": "Upgrade OpenSSL package and restart affected services.",
        "owner": "Engineering",
        "status": RemediationStatus.COMPLETED,
        "priority": Severity.HIGH,
        "due_offset_days": -2,
        "finding_title": "Outdated OpenSSL (CVE-2023-0286)",
    },
]
